### ISSUE TITLE
Basic custom authentication seems to be failing

### ISSUE THREAD

**Issue by a1an77** [boundlessgeo/gsconfig#103]
I just tried the example :

    from geoserver.catalog import Catalog 
    cat = Catalog("http://localhost:8080/geoserver/rest/") 
    cat.username = "admin"
    cat.password = passw
    ws = cat.get_workspace(ws_name)

with gsconfig 0.6.13 on geoserver 2.7.1 this results in the following error:

Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces.xml but got a 401 status code: 

    [...]
    No AuthenticationProvider found for       
    org.springframework.security.authentication.UsernamePasswordAuthenticationToken</u></p><p>
    <b>description</b> <u>This request requires HTTP authentication (No AuthenticationProvider 
    found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken).
    [...]

**Comment by BerryDaniel** [comment]
A 401 status means unauthorized. Could you possibly not have the correct password. I have successfully  tested the following on a vanilla GeoServer 2.7.1 using the following snippet in a script:

```
from geoserver.catalog import Catalog

cat = Catalog("http://localhost:8080/geoserver/rest/")
cat.username = "admin"
cat.password = "geoserver"
ws = cat.get_workspace("cite")
print ws.name
print cat.gsversion()
```

Output

```
cite
2.7.1
```

**Comment by a1an77** [comment]
I'm quite sure the password was correct. Meanwhile I wrote my own configurator for it so I cannot provide further insight on that one at the moment.
