### ISSUE TITLE
Error when trying to save None value in resource.metadata_links

### ISSUE THREAD

**Issue by cristianzamar** [boundlessgeo/gsconfig#108]
I was trying to update some resources attributes when I got this error: 
```
cat_dest.save(rd)
  File "build/bdist.linux-i686/egg/geoserver/catalog.py", line 238, in save
  File "build/bdist.linux-i686/egg/geoserver/support.py", line 196, in message
  File "build/bdist.linux-i686/egg/geoserver/support.py", line 191, in serialize
  File "build/bdist.linux-i686/egg/geoserver/resource.py", line 31, in write
TypeError: 'NoneType' object is not iterable
```
I went to [that line](https://github.com/boundlessgeo/gsconfig/blob/2202e1906913b88d1c1f8d5c4633bd600b84ffd0/src/geoserver/resource.py#L31) and found the error was in the for loop, so I sent an empty array instead of None.

*Maybe a validation there would make it easier.*
my script [here](https://gist.github.com/cristianzamar/fc07d0b9c88665fa709e)

**Comment by BerryDaniel** [comment]
@cristianzamar 

I ran a test based off of what you had in your script and I did not receive an error when trying to save a None value in resource.metadata_links. I tested this on a vanilla 2.7.2 version and cascaded the sfdem layer and named it wms_sfdem.

Are you still having this issue? 
What version of GeoServer are you using?

Tested the following:
```
from geoserver.catalog import Catalog

cat = Catalog("http://localhost:8080/geoserver/rest/", "admin", "***")
print "GeoServer Version %s" % cat.gsversion()
resources = cat.get_resources()
count = 0

for resource in resources:
    if resource.resource_type != "wmsLayer": continue
    print "metadata_links value: %s" % resource.metadata_links
    cat.save(resource)
    cat.reload()
    print "Updated layer: %s" % resource.name
    count += 1

print "Total updated layers: %s" % count
```

Output:
```
GeoServer Version 2.7.2
metadata_links value: None
Updated layer: wms_sfdem
Total updated layers: 1
```

**Comment by cristianzamar** [comment]
@BerryDaniel 
Thanks for your response.

The target GS version is 2.4.2 and I am still having this issue.
I tested your script and it worked, but I found it's not actually modifying a _metadata_links_ attribute. You can try setting _resource.metadata_links_ to a None value and I think you will get the error.

**Comment by afabiani** [comment]
Hi Christian,
the method "resources = cat.get_resources()" already gets the layers
resources which is equivalent to do layer.resource.metadata_links

I'm going to test this too and let you know.

I will also try with a vanilla GS 2.4.2 war.

Regards,
Alessio Fabiani.



==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by afabiani** [comment]
I confirm that works with GeoServer 2.7.x

*Output:*
GeoServer Version 2.7-SNAPSHOT
metadata_links value: None
Updated layer: world
metadata_links value: None
Updated layer: medford
metadata_links value: None
Updated layer: medford_bikelanes
metadata_links value: None
Updated layer: opengeo_borders
metadata_links value: None
Updated layer: medford_buildings
metadata_links value: None
Updated layer: opengeo_cities
metadata_links value: None
Updated layer: medford_citylimits
metadata_links value: None
Updated layer: opengeo_countries
metadata_links value: None
Updated layer: medford_elevation
metadata_links value: None
Updated layer: medford_firestations
metadata_links value: None
Updated layer: medford_hospitals
metadata_links value: None
Updated layer: medford_hydro
metadata_links value: None
Updated layer: medford_libraries
metadata_links value: None
Updated layer: medford_parks
metadata_links value: None
Updated layer: medford_police
metadata_links value: None
Updated layer: medford_schools
metadata_links value: None
Updated layer: usa_states
metadata_links value: None
Updated layer: medford_stormdrains
metadata_links value: None
Updated layer: medford_streets
metadata_links value: None
Updated layer: medford_taxlots
metadata_links value: None
Updated layer: medford_wetlands
metadata_links value: None
Updated layer: medford_zoning
Total updated layers: 22

It seems working with GeoServer 2.4.2 too

*Updated code:*
from geoserver.catalog import Catalog

cat = Catalog("http://localhost:8080/geoserver/rest/", "admin", "geoserver")
print "GeoServer Version %s" % cat.gsversion()
layers = cat.get_layers()
count = 0

for layer in layers:
    resource = layer.resource
    # if resource.resource_type != "wmsLayer": continue
    print "metadata_links value: %s" % resource.metadata_links
    cat.save(resource)
    cat.reload()
    print "Updated layer: %s" % resource.name
    count += 1

print "Total updated layers: %s" % count


*Output:*
GeoServer Version 2.4.2
metadata_links value: None
Updated layer: roads
metadata_links value: None
Updated layer: archsites
metadata_links value: None
Updated layer: streams
metadata_links value: None
Updated layer: restricted
metadata_links value: None
Updated layer: bugsites
metadata_links value: None
Updated layer: sfdem
metadata_links value: None
Updated layer: tasmania_cities
metadata_links value: None
Updated layer: tasmania_water_bodies
metadata_links value: None
Updated layer: tasmania_state_boundaries
metadata_links value: None
Updated layer: tasmania_roads
metadata_links value: None
Updated layer: states
metadata_links value: None
Updated layer: Img_Sample
metadata_links value: None
Updated layer: mosaic
metadata_links value: None
Updated layer: Arc_Sample
metadata_links value: None
Updated layer: Pk50095
metadata_links value: None
Updated layer: giant_polygon
metadata_links value: None
Updated layer: poly_landmarks
metadata_links value: None
Updated layer: tiger_roads
metadata_links value: None
Updated layer: poi
Total updated layers: 19


==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by cristianzamar** [comment]
Thanks @afabiani 
I think the problem is not the GS version but the resource.py script itself.
I tried setting ```rd.metadata_links = None``` at [this line](https://gist.github.com/cristianzamar/fc07d0b9c88665fa709e#file-update_wmslayers-py-L32) and got the same error.

Can you try it that way?

**Comment by afabiani** [comment]
Cristian you are right,
I just found an issue into the resource module trying to iterate on a None
object.

I'll open the ticket and commit the patch.

Thanks for your help,
-A.


==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by afabiani** [comment]
The error is reproducible with the script from Christian

https://gist.github.com/cristianzamar/fc07d0b9c88665fa709e#file-update_wmslayers-py-L32

Going to commit a PR for this,
-A.

**Comment by afabiani** [comment]
PR ready here

https://github.com/boundlessgeo/gsconfig/pull/129


==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by cristianzamar** [comment]
Thanks @afabiani !!
I am really glad I could collaborate here.
