### ISSUE TITLE
pip install gsconfig

### ISSUE THREAD

**Issue by andysims** [boundlessgeo/gsconfig#198]
Error when running "pip install gsconfig." 

Here's the error I receive...

Collecting gsconfig
  Using cached https://files.pythonhosted.org/packages/a1/f2/2bde043ed1238643e6459674ac75534defecde2ff13b1532eccb732c0bd8/gsconfig-1.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/md/16zrp6t13r9g0y_0c2vl4q740000gn/T/pip-install-626nj8ti/gsconfig/setup.py", line 8
        except IOError,e:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/md/16zrp6t13r9g0y_0c2vl4q740000gn/T/pip-install-626nj8ti/gsconfig/

**Comment by SSaeedHoseini** [comment]
Try this command  'pip install gsconfig-py3'

**Comment by JoelBennett** [comment]
Seems to me like it isn't Python 3 compatible.

**Comment by adclose** [comment]
has there been a solution found for this?

**Comment by JoelBennett** [comment]
Not that I'm aware of - unless someone has forked the repo and fixed it.

**Comment by adclose** [comment]
just found a solution its related to python 3 compaitiblity use the gsconfig-py3 lib instead

**Comment by kensongzhu** [comment]
The code is already python3-compatible on **master**, it is just the fact that no new realase is available 
 on PyPI.  It seems that **gsconfig-py3** is not always up2date as it states. 
 
Here is the alternative. You can always install the master branch if this happens.

If you use **pip**
```sh
pip install git+https://github.com/boundlessgeo/gsconfig.git#master
```
if you use **pipenv**
```sh
pipenv install -e git+https://github.com/boundlessgeo/gsconfig.git@master#egg=gsconfig
```

PS: 
- if you use **pipenv**, and writing private repo on top of **gsconfig**, use pip instead. It will be a headache when it comes to packaging your private repo. 
- If your stuff eventually goes to server, and the server blocks git, use **gsconfig-py3** 

Just curiours, why isn't there any new release on PyPI?  Is there any decision being made that I miss from this repo?

**Comment by andysims** [comment]
@adclose using gsconfig-py3 worked. Thank you very much. I apologize for the late response.

**Comment by Shivangi373** [comment]
You can try this command for python 3

pip install gsconfig-py3
