### ISSUE TITLE
Metadata in datastores not showing up through xml from geoserver.

### ISSUE THREAD

**Issue by wwk3j** [boundlessgeo/gsconfig#21]
I'm writing a script to use in ArcMap that quickexports to PostGIS and then creates a datastore that points to geoserver. I've been able to create a datastore, but I've noticed that looking at the document tree associated with those datastores they are missing styles. I'm fairly new at this and learning Python on the fly. So I guess that one guy that had the comment about postgis is roughly similar to mine except I'm not quite so used to forking and was wondering if there was something in the gsconfig that could establish a wrapper class to postgis. I know the catalog test shows this is possible, but I can't seem to figure out how.

**Comment by garnertb** [comment]
Closing this since its three years old and unclear whether there is actually an issue here.
