### ISSUE TITLE
cat.save(layer) fails to actually save changes to a layer

### ISSUE THREAD

**Issue by JoelBennett** [boundlessgeo/gsconfig#87]
I'm not sure if anyone else is seeing this, but it is annoying as heck.  The following snippet of code should enable all layers in GeoServer..except that it doesn't.  When looking at the layers through the GeoServer web interface, there's no change to a layer's enabled flag.

    from geoserver.catalog import Catalog
    cat = Catalog("http://localhost:8080/geoserver/rest", "admin", "geoserver")
    layers = cat.get_layers()
    for layer in layers:
        layer = cat.get_layer(layer.name)
        layer.enabled = False
        cat.save(layer)

Attempting to call cat.reload() after every save has no effect.

**Comment by BerryDaniel** [comment]
@JoelBennett The issue is with the documentation. The above steps only work with GeoServer version <= 2.3. GeoServer version >= 2.4 handle enabling and disabling the layers at the resource level.

This would disable all layers in GeoServer.

```
from geoserver.catalog import Catalog
cat = Catalog("http://localhost:8080/geoserver/rest", "admin", "geoserver")
resources = cat.get_resources()
for resource in resources:
    resource.enabled = False
    cat.save(resource)
```

**Comment by JoelBennett** [comment]
Good to know.  Thanks.
