### ISSUE TITLE
test failures on geoserver 2.6

### ISSUE THREAD

**Issue by ischneider** [boundlessgeo/gsconfig#89]
Looks related to recent catalog validation efforts:

- [ ] **testCoverageStoreCreate**
  This seems to be because we're not writing the workspace as part of the XML request
- [x] **testWmsLayer**
  This appears to be because the layer name contains a colon (invalid XML) - instead, we need to sanitize this and also provide the nativeName

**Comment by garnertb** [comment]
Both testWmsLayer and testCoverageCreate are passing on Geoserver 2.4-2.8.  Closing.
